---
title: "analysis of my grade"
author: "Abby Lin"
date: "11/04/2020"
output:
  md_document: default
---

```{r libraries}
library(dplyr)
library(tidyverse)
library(readr)
```

import csv file

```{r csv import}
grades <- read.csv("grades.csv")
head(grades)
```

add subject GPA column
```{r sub_gpa}
grades.s <- grades%>%
  filter(grade.in.words == "S")%>%
  mutate(sub_gpa = 4)
grades.a <- grades%>%
  filter(grade.in.words == "A")%>%
  mutate(sub_gpa = 3)
grades <- grades.s%>%
  bind_rows(grades.a)
```

add total gpa column

```{r tol_gpa}
grades <- grades%>%
  mutate(tol_gpa = sub_gpa * Credits)%>%
  select(-"Course.Sub.category", -"Course.Name", -"Year.Completed", -"Semester.Completed")%>%
  rbind(list(2,'S',4,8))%>%
  rbind(list(2,'S',4,8))%>%
  rbind(list(6,'B',2,12))
head(grades)
```
calculate average gpa

```{r average gpa}
total_points <- sum(grades$tol_gpa)
total_credits <- sum(grades$Credits)
average_gpa <- total_points / total_credits

print(paste0("My average GPA up til now is: ", average_gpa))
```